/**
 * Extracts the brand SVGs in assets/brand into lib/generated/art.ts.
 *
 * Why this exists rather than inlining the files directly:
 *
 *  1. Every traced SVG carries its own <style> block with identical `.edge` /
 *     `.ink` classes and `@keyframes draw`. Inline five of them into one document
 *     and the rules collide — last one wins — and all five fire on page load
 *     instead of on scroll. Stripping the styles once, here, means the app owns
 *     when each one animates.
 *
 *  2. The two paths in each Warli export share the SAME `d` (one stroked as the
 *     outline, one filled). Storing it once halves the payload.
 *
 * Run: node scripts/extract-art.mjs   (wired to prebuild)
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'assets', 'brand');
const OUT = join(ROOT, 'lib', 'generated', 'art.ts');

/** The client's own mapping of trace file -> pillar. */
const WARLI_MAP = {
  'warli-1.svg': 'doorstep',
  'warli-2.svg': 'customers',
  'warli-3.svg': 'pure',
  'warli-4.svg': 'cows',
  'warli-5.svg': 'farmers',
};

const read = f => readFileSync(join(SRC, f), 'utf8');

function viewBox(svg, file) {
  const m = svg.match(/viewBox="([^"]+)"/);
  if (!m) throw new Error(`${file}: no viewBox`);
  const nums = m[1].trim().split(/\s+/).map(Number);
  if (nums.length !== 4 || nums.some(Number.isNaN)) throw new Error(`${file}: bad viewBox "${m[1]}"`);
  return nums;
}

/** Longest `d` wins — a frame or background path is always far shorter. */
function longestPath(svg, file) {
  const ds = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map(m => m[1]);
  if (!ds.length) throw new Error(`${file}: no <path d="...">`);
  return ds.reduce((a, b) => (b.length > a.length ? b : a));
}

function circles(svg) {
  return [...svg.matchAll(/<circle[^>]*\/>/g)].map(m => {
    const g = a => Number((m[0].match(new RegExp(`${a}="([^"]+)"`)) ?? [])[1] ?? 0);
    return { x: g('cx'), y: g('cy'), r: g('r') || 4 };
  });
}

const kolamSvg = read('kolam.svg');
const kolam = {
  viewBox: viewBox(kolamSvg, 'kolam.svg'),
  path: longestPath(kolamSvg, 'kolam.svg'),
  dots: circles(kolamSvg),
};
if (kolam.dots.length === 0) throw new Error('kolam.svg: no pulli found — refusing to emit a dotless kolam');

const warli = {};
for (const [file, key] of Object.entries(WARLI_MAP)) {
  const svg = read(file);
  warli[key] = { viewBox: viewBox(svg, file), path: longestPath(svg, file) };
}

/* ---------------------------------------------------------------------------
 * The wordmark, from the client's vector PDF (pdftocairo output).
 *
 * That file is the real logo: 39 paths, zero images. The white-filled paths are
 * the art, the red one is the field. The kolam sits above the wordmark, so a
 * single Y split separates them — which gives us the actual typeface as outlines
 * instead of approximating it with a system serif.
 *
 * pdftocairo emits absolute M/L/C commands only, so numbers alternate x,y and a
 * crude bbox scan is reliable here.
 * ------------------------------------------------------------------------- */
function bboxY(d) {
  const nums = d.match(/-?\d*\.?\d+/g);
  if (!nums) return { min: 0, max: 0 };
  let min = Infinity, max = -Infinity;
  for (let i = 1; i < nums.length; i += 2) {
    const y = Number(nums[i]);
    if (y < min) min = y;
    if (y > max) max = y;
  }
  return { min, max };
}

let wordmark = null;
try {
  const vec = read('logo-vector.svg');
  const vb = viewBox(vec, 'logo-vector.svg');
  const whites = [...vec.matchAll(/<path[^>]*fill="rgb\(100%,\s*100%,\s*100%\)"[^>]*\sd="([^"]+)"/g)].map(m => m[1]);
  const alt = whites.length
    ? whites
    : [...vec.matchAll(/<path[^>]*\sd="([^"]+)"[^>]*fill="rgb\(100%,\s*100%,\s*100%\)"/g)].map(m => m[1]);
  const parts = alt.map(d => ({ d, y: bboxY(d) })).filter(p => Number.isFinite(p.y.min));
  if (parts.length) {
    // split where the vertical gap between sorted paths is widest in the middle
    const SPLIT = vb[3] * 0.46;
    const lower = parts.filter(p => p.y.min > SPLIT);
    if (lower.length) {
      const minY = Math.min(...lower.map(p => p.y.min));
      const maxY = Math.max(...lower.map(p => p.y.max));
      wordmark = {
        viewBox: [0, Math.round(minY - 6), vb[2], Math.round(maxY - minY + 12)],
        paths: lower.map(p => p.d),
      };
    }
  }
} catch {
  console.warn('logo-vector.svg not found — wordmark falls back to type');
}

const banner = `// GENERATED by scripts/extract-art.mjs — do not edit by hand.
// Source: assets/brand/*.svg. Style blocks are stripped on purpose; the app owns
// when this art animates. Regenerate with: node scripts/extract-art.mjs
`;

const body = `${banner}
export interface Art { viewBox: readonly [number, number, number, number]; path: string }
export interface Dot { x: number; y: number; r: number }

export const KOLAM: Art & { dots: readonly Dot[] } = ${JSON.stringify(kolam, null, 2)} as const;

export type WarliKey = ${Object.values(WARLI_MAP).map(k => `'${k}'`).join(' | ')};

export const WARLI: Record<WarliKey, Art> = ${JSON.stringify(warli, null, 2)} as const;

/** The real wordmark as outlines, from the client's vector PDF. */
export const WORDMARK: { viewBox: readonly [number, number, number, number]; paths: readonly string[] } | null =
  ${JSON.stringify(wordmark, null, 2)};
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, body);

const kb = n => (n / 1024).toFixed(1) + ' KB';
console.log(`kolam  ${kolam.dots.length} dots · path ${kb(kolam.path.length)} · viewBox ${kolam.viewBox.join(' ')}`);
for (const [key, a] of Object.entries(warli)) {
  console.log(`warli  ${key.padEnd(10)} path ${kb(a.path.length).padStart(9)} · viewBox ${a.viewBox.join(' ')}`);
}
const total = Object.values(warli).reduce((n, a) => n + a.path.length, 0);
console.log(`\n-> ${OUT.replace(ROOT + '/', '')}  (warli total ${kb(total)} raw)`);
