/**
 * Extracts the brand SVGs in assets/brand into lib/generated/art.ts.
 *
 * Why this exists rather than inlining the files directly:
 *
 *  1. Every traced SVG carries its own <style> block with identical `.edge` /
 *     `.ink` classes and `@keyframes draw`. Inline five of them into one document
 *     and the rules collide — last one wins — and all five fire on page load
 *     instead of on scroll. Stripping the styles once, here, means the app owns
 *     when each one animates.
 *
 *  2. The two paths in each Warli export share the SAME `d` (one stroked as the
 *     outline, one filled). Storing it once halves the payload.
 *
 * Run: node scripts/extract-art.mjs   (wired to prebuild)
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'assets', 'brand');
const OUT = join(ROOT, 'lib', 'generated', 'art.ts');

/** The client's own mapping of trace file -> pillar. */
const WARLI_MAP = {
  'warli-1.svg': 'doorstep',
  'warli-2.svg': 'customers',
  'warli-3.svg': 'pure',
  'warli-4.svg': 'cows',
  'warli-5.svg': 'farmers',
};

const read = f => readFileSync(join(SRC, f), 'utf8');

function viewBox(svg, file) {
  const m = svg.match(/viewBox="([^"]+)"/);
  if (!m) throw new Error(`${file}: no viewBox`);
  const nums = m[1].trim().split(/\s+/).map(Number);
  if (nums.length !== 4 || nums.some(Number.isNaN)) throw new Error(`${file}: bad viewBox "${m[1]}"`);
  return nums;
}

/** Longest `d` wins — a frame or background path is always far shorter. */
function longestPath(svg, file) {
  const ds = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map(m => m[1]);
  if (!ds.length) throw new Error(`${file}: no <path d="...">`);
  return ds.reduce((a, b) => (b.length > a.length ? b : a));
}

function circles(svg) {
  return [...svg.matchAll(/<circle[^>]*\/>/g)].map(m => {
    const g = a => Number((m[0].match(new RegExp(`${a}="([^"]+)"`)) ?? [])[1] ?? 0);
    return { x: g('cx'), y: g('cy'), r: g('r') || 4 };
  });
}

const kolamSvg = read('kolam.svg');
const kolam = {
  viewBox: viewBox(kolamSvg, 'kolam.svg'),
  path: longestPath(kolamSvg, 'kolam.svg'),
  dots: circles(kolamSvg),
};
if (kolam.dots.length === 0) throw new Error('kolam.svg: no pulli found — refusing to emit a dotless kolam');

const warli = {};
for (const [file, key] of Object.entries(WARLI_MAP)) {
  const svg = read(file);
  warli[key] = { viewBox: viewBox(svg, file), path: longestPath(svg, file) };
}

const banner = `// GENERATED by scripts/extract-art.mjs — do not edit by hand.
// Source: assets/brand/*.svg. Style blocks are stripped on purpose; the app owns
// when this art animates. Regenerate with: node scripts/extract-art.mjs
`;

const body = `${banner}
export interface Art { viewBox: readonly [number, number, number, number]; path: string }
export interface Dot { x: number; y: number; r: number }

export const KOLAM: Art & { dots: readonly Dot[] } = ${JSON.stringify(kolam, null, 2)} as const;

export type WarliKey = ${Object.values(WARLI_MAP).map(k => `'${k}'`).join(' | ')};

export const WARLI: Record<WarliKey, Art> = ${JSON.stringify(warli, null, 2)} as const;
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, body);

const kb = n => (n / 1024).toFixed(1) + ' KB';
console.log(`kolam  ${kolam.dots.length} dots · path ${kb(kolam.path.length)} · viewBox ${kolam.viewBox.join(' ')}`);
for (const [key, a] of Object.entries(warli)) {
  console.log(`warli  ${key.padEnd(10)} path ${kb(a.path.length).padStart(9)} · viewBox ${a.viewBox.join(' ')}`);
}
const total = Object.values(warli).reduce((n, a) => n + a.path.length, 0);
console.log(`\n-> ${OUT.replace(ROOT + '/', '')}  (warli total ${kb(total)} raw)`);
